import { 
  SubscriptionPlanId, 
  SubscriptionPlanConfig, 
  FeatureComparisonCategory,
  FeatureKey
} from '../types';

export const SUBSCRIPTION_PLANS: Record<SubscriptionPlanId, SubscriptionPlanConfig> = {
  free: {
    id: 'free',
    name: 'Free',
    tagline: 'For users trying Socially.',
    monthlyPrice: 0,
    yearlyPrice: 0,
    yearlyPriceMonthlyEquivalent: 0,
    savingPercentage: 0,
    ctaText: 'Start Free',
    isPopular: false,
    badgeText: 'Basic',
    limits: {
      socialAccounts: 2,
      teamMembers: 1,
      scheduledPosts: 10,
      aiGenerations: 10,
      workspaces: 1,
    },
    features: [
      '2 social accounts',
      '1 team member',
      '10 scheduled posts/month',
      'Basic analytics',
      'Basic content calendar',
      'Events & Days calendar',
      '10 AI generations/month',
      'Basic media library',
      'Limited AI assistant',
    ],
    unlockedFeatures: [
      'basic_analytics',
      'basic_calendar',
      'events_calendar',
      'basic_media',
      'limited_ai',
    ],
  },
  creator: {
    id: 'creator',
    name: 'Creator',
    tagline: 'For individual creators & solopreneurs.',
    monthlyPrice: 299,
    yearlyPrice: 2990,
    yearlyPriceMonthlyEquivalent: 249,
    savingPercentage: 17,
    ctaText: 'Upgrade to Creator',
    isPopular: false,
    badgeText: 'Solo Pro',
    limits: {
      socialAccounts: 5,
      teamMembers: 1,
      scheduledPosts: 'unlimited',
      aiGenerations: 100,
      workspaces: 1,
    },
    features: [
      '5 social accounts',
      '1 team member',
      'Unlimited scheduled posts',
      'Advanced content calendar',
      'Advanced analytics',
      'AI captions, hashtags & ideas',
      '100 AI generations/month',
      'Full media library',
      'Socially AI Content Generator',
      'Content Analyzer',
      'Events & Days with AI Hooks',
      'Basic notifications',
    ],
    unlockedFeatures: [
      'basic_analytics',
      'advanced_analytics',
      'basic_calendar',
      'advanced_calendar',
      'events_calendar',
      'basic_media',
      'media_library',
      'limited_ai',
      'socially_ai',
      'ai_captions',
      'ai_hashtags',
      'ai_content_ideas',
      'content_analyzer',
      'unlimited_scheduling',
    ],
  },
  team: {
    id: 'team',
    name: 'Team',
    tagline: 'For marketing teams, colleges & high-velocity brands.',
    monthlyPrice: 799,
    yearlyPrice: 7990,
    yearlyPriceMonthlyEquivalent: 666,
    savingPercentage: 17,
    ctaText: 'Start Team',
    isPopular: true,
    badgeText: 'MOST POPULAR',
    limits: {
      socialAccounts: 15,
      teamMembers: 10,
      scheduledPosts: 'unlimited',
      aiGenerations: 500,
      workspaces: 1,
    },
    features: [
      '15 social accounts',
      '10 team members',
      'Unlimited scheduled posts',
      'Advanced analytics & reports',
      'AI content generation suite',
      'AI Reel & Short scripts',
      'AI Content Radar',
      'Video Prompt Lab',
      'Content Analyzer',
      'Campaign management',
      'Tasks & kanban workflow',
      'Team Chat & live messaging',
      'Multi-stage Approvals',
      'Team member granular roles',
      'Shared media library',
      'Smart notifications & AI signals',
      '500 AI generations/month',
    ],
    unlockedFeatures: [
      'basic_analytics',
      'advanced_analytics',
      'basic_calendar',
      'advanced_calendar',
      'events_calendar',
      'basic_media',
      'media_library',
      'shared_media',
      'limited_ai',
      'socially_ai',
      'ai_captions',
      'ai_hashtags',
      'ai_content_ideas',
      'ai_reel_scripts',
      'ai_content_radar',
      'video_prompt_lab',
      'content_analyzer',
      'unlimited_scheduling',
      'campaigns',
      'tasks_workflow',
      'team_chat',
      'approvals',
      'team_roles',
      'smart_notifications',
    ],
  },
  pro: {
    id: 'pro',
    name: 'Pro',
    tagline: 'For agencies, multi-campus colleges and organizations.',
    monthlyPrice: 1499,
    yearlyPrice: 14990,
    yearlyPriceMonthlyEquivalent: 1249,
    savingPercentage: 17,
    ctaText: 'Upgrade to Pro',
    isPopular: false,
    badgeText: 'Agency / Enterprise Tier',
    limits: {
      socialAccounts: 50,
      teamMembers: 25,
      scheduledPosts: 'unlimited',
      aiGenerations: 2000,
      workspaces: 5,
    },
    features: [
      '50 social accounts',
      '25 team members',
      'Unlimited scheduled posts',
      'Advanced multi-channel analytics',
      'Multiple workspaces (up to 5)',
      'Advanced Campaign management',
      'Advanced AI assistant suite',
      'AI Content Radar & Trends',
      'Competitor & content insights',
      'AI performance recommendations',
      'Advanced approval workflows',
      'White-label client reports',
      'Priority 24/7 support',
      '2,000 AI generations/month',
    ],
    unlockedFeatures: [
      'basic_analytics',
      'advanced_analytics',
      'basic_calendar',
      'advanced_calendar',
      'events_calendar',
      'basic_media',
      'media_library',
      'shared_media',
      'limited_ai',
      'socially_ai',
      'ai_captions',
      'ai_hashtags',
      'ai_content_ideas',
      'ai_reel_scripts',
      'ai_content_radar',
      'video_prompt_lab',
      'content_analyzer',
      'unlimited_scheduling',
      'campaigns',
      'tasks_workflow',
      'team_chat',
      'approvals',
      'team_roles',
      'smart_notifications',
      'multiple_workspaces',
      'competitor_insights',
      'white_label_reports',
      'priority_support',
      'custom_workflows',
    ],
  },
  enterprise: {
    id: 'enterprise',
    name: 'Enterprise',
    tagline: 'For large educational trusts, conglomerates & global agencies.',
    monthlyPrice: 0,
    yearlyPrice: 0,
    yearlyPriceMonthlyEquivalent: 0,
    savingPercentage: 0,
    ctaText: "Let's Talk",
    isPopular: false,
    badgeText: 'Custom Solution',
    limits: {
      socialAccounts: 100,
      teamMembers: 100,
      scheduledPosts: 'unlimited',
      aiGenerations: 10000,
      workspaces: 20,
    },
    features: [
      '100+ social accounts',
      'Custom team size',
      'Multiple organizations / workspaces',
      'Full REST & Webhook API access',
      'Custom integrations (ERP, Slack, WhatsApp)',
      'Custom fine-tuned AI workflows',
      'Dedicated Customer Success Manager',
      '99.9% Uptime SLA',
      'Custom pricing & invoicing',
    ],
    unlockedFeatures: [
      'basic_analytics',
      'advanced_analytics',
      'basic_calendar',
      'advanced_calendar',
      'events_calendar',
      'basic_media',
      'media_library',
      'shared_media',
      'limited_ai',
      'socially_ai',
      'ai_captions',
      'ai_hashtags',
      'ai_content_ideas',
      'ai_reel_scripts',
      'ai_content_radar',
      'video_prompt_lab',
      'content_analyzer',
      'unlimited_scheduling',
      'campaigns',
      'tasks_workflow',
      'team_chat',
      'approvals',
      'team_roles',
      'smart_notifications',
      'multiple_workspaces',
      'competitor_insights',
      'white_label_reports',
      'priority_support',
      'custom_workflows',
      'api_access',
      'dedicated_csm',
    ],
  },
};

export const FEATURE_COMPARISON_CATEGORIES: FeatureComparisonCategory[] = [
  {
    categoryName: 'Social Accounts & Publishing',
    features: [
      {
        name: 'Connected Social Accounts',
        free: '2 accounts',
        creator: '5 accounts',
        team: '15 accounts',
        pro: '50 accounts',
        enterprise: '100+ accounts',
      },
      {
        name: 'Scheduled Posts Limit',
        free: '10 / month',
        creator: 'Unlimited',
        team: 'Unlimited',
        pro: 'Unlimited',
        enterprise: 'Unlimited',
      },
      {
        name: 'Instagram, FB, X, LinkedIn, YT, TikTok',
        free: true,
        creator: true,
        team: true,
        pro: true,
        enterprise: true,
      },
      {
        name: 'Multi-Account Bulk Publishing',
        free: false,
        creator: true,
        team: true,
        pro: true,
        enterprise: true,
      },
      {
        name: 'Auto First-Comment Hashtags',
        free: false,
        creator: true,
        team: true,
        pro: true,
        enterprise: true,
      },
    ],
  },
  {
    categoryName: 'Content Calendar & Planning',
    features: [
      {
        name: 'Content Calendar View (Month/Week/List)',
        free: 'Basic month view',
        creator: 'Full interactive',
        team: 'Full interactive',
        pro: 'Full interactive',
        enterprise: 'Full + Multi-workspace',
      },
      {
        name: 'India & Global Events Calendar (150+ Days)',
        free: true,
        creator: true,
        team: true,
        pro: true,
        enterprise: true,
      },
      {
        name: 'AI Event Opportunity Signals',
        free: '2 days advance',
        creator: '7 days advance',
        team: '30 days advance',
        pro: 'Year-round radar',
        enterprise: 'Custom radar',
      },
    ],
  },
  {
    categoryName: 'AI Superpowers & Generation',
    features: [
      {
        name: 'Monthly AI Generations',
        free: '10 credits',
        creator: '100 credits',
        team: '500 credits',
        pro: '2,000 credits',
        enterprise: 'Unlimited / Custom',
      },
      {
        name: 'Socially AI Multi-Platform Generator',
        free: 'Basic copy only',
        creator: true,
        team: true,
        pro: true,
        enterprise: true,
      },
      {
        name: 'AI Content Radar & Viral Trends',
        free: false,
        creator: false,
        team: true,
        pro: true,
        enterprise: true,
      },
      {
        name: 'AI Reel & Short Scriptwriter with Shotlists',
        free: false,
        creator: false,
        team: true,
        pro: true,
        enterprise: true,
      },
      {
        name: 'Video Prompt Lab (Sora/Runway/Pika Prompts)',
        free: false,
        creator: false,
        team: true,
        pro: true,
        enterprise: true,
      },
      {
        name: 'AI Content Analyzer & Virality Scoring',
        free: false,
        creator: true,
        team: true,
        pro: true,
        enterprise: true,
      },
    ],
  },
  {
    categoryName: 'Analytics & Reporting',
    features: [
      {
        name: 'Analytics History Window',
        free: '7 days',
        creator: '30 days',
        team: '1 year',
        pro: 'Lifetime',
        enterprise: 'Lifetime + Data Lake',
      },
      {
        name: 'Audience Demographics & Growth Trends',
        free: 'Basic',
        creator: 'Detailed',
        team: 'Comprehensive',
        pro: 'Multi-campus/brand',
        enterprise: 'Custom BI export',
      },
      {
        name: 'Competitor Benchmarking & Insights',
        free: false,
        creator: false,
        team: 'Basic',
        pro: true,
        enterprise: true,
      },
      {
        name: 'White-label PDF & Presentation Reports',
        free: false,
        creator: false,
        team: false,
        pro: true,
        enterprise: true,
      },
    ],
  },
  {
    categoryName: 'Team Collaboration & Governance',
    features: [
      {
        name: 'Team Members Seats',
        free: '1 member',
        creator: '1 member',
        team: '10 members',
        pro: '25 members',
        enterprise: 'Unlimited custom',
      },
      {
        name: 'Multi-Stage Content Approvals',
        free: false,
        creator: false,
        team: true,
        pro: 'Advanced custom',
        enterprise: 'Hierarchical HOD/Exec',
      },
      {
        name: 'Tasks & Kanban Management',
        free: false,
        creator: false,
        team: true,
        pro: true,
        enterprise: true,
      },
      {
        name: 'Team Chat & Direct Mentions',
        free: false,
        creator: false,
        team: true,
        pro: true,
        enterprise: true,
      },
      {
        name: 'Granular Role-Based Access Control',
        free: false,
        creator: false,
        team: true,
        pro: true,
        enterprise: 'SSO & SAML mapping',
      },
    ],
  },
  {
    categoryName: 'Campaigns & Media Assets',
    features: [
      {
        name: 'Campaign Management Suite',
        free: false,
        creator: false,
        team: true,
        pro: true,
        enterprise: true,
      },
      {
        name: 'Media Asset Storage',
        free: '500 MB',
        creator: '10 GB',
        team: '50 GB',
        pro: '250 GB',
        enterprise: 'Unlimited Cloud',
      },
      {
        name: 'Shared Team Asset Folders & Tags',
        free: false,
        creator: false,
        team: true,
        pro: true,
        enterprise: true,
      },
    ],
  },
  {
    categoryName: 'Support & Infrastructure',
    features: [
      {
        name: 'Support Level',
        free: 'Community / Email',
        creator: 'Standard Email',
        team: 'Priority Chat & Email',
        pro: '24/7 Dedicated Support',
        enterprise: 'Dedicated CSM + SLA',
      },
      {
        name: 'Multiple Workspaces',
        free: '1',
        creator: '1',
        team: '1',
        pro: '5 Workspaces',
        enterprise: 'Unlimited Workspaces',
      },
      {
        name: 'API & Webhook Access',
        free: false,
        creator: false,
        team: false,
        pro: false,
        enterprise: true,
      },
    ],
  },
];

/**
 * Checks if a plan has access to a specific feature key.
 */
export function hasFeatureAccess(planId: SubscriptionPlanId, feature: FeatureKey): boolean {
  const plan = SUBSCRIPTION_PLANS[planId];
  if (!plan) return false;
  return plan.unlockedFeatures.includes(feature);
}

/**
 * Returns the minimum required plan to unlock a given feature.
 */
export function getRequiredPlanForFeature(feature: FeatureKey): SubscriptionPlanId {
  const hierarchy: SubscriptionPlanId[] = ['free', 'creator', 'team', 'pro', 'enterprise'];
  for (const planId of hierarchy) {
    if (SUBSCRIPTION_PLANS[planId].unlockedFeatures.includes(feature)) {
      return planId;
    }
  }
  return 'team';
}
